use Rex -feature => [qw/1.4 exec_autodie/];

# Define the host groups
group head     => 'compute01';
group workers  => 'compute02', 'compute03';
group allnodes => 'compute01', 'compute02', 'compute03';

# Set the SSH user (replace with your actual username)
user "user";
sudo TRUE;
sudo_password "$ENV{SUDOPASS}";

# Main task to install and configure Chrony
desc "Ensure slurm is installed and configured";
task "setup_slurm", group => "allnodes", sub {
  my $hostname = connection->server;
  my $is_head  = ($hostname eq 'compute01');

  say run "uname -a";

  # Install Chrony
  pkg "slurm-wlm", ensure => "present";
  pkg "munge",     ensure => "present";

  if ($is_head) {
    # generate munge key on head node
    if (not is_file "/etc/munge/munge.key") {
      run "mungekey --create";
    }
    # copy to make available on other nodes
    if (is_file "/etc/munge/munge.key" and not is_file "/mnt/home/munge.key") {
        file '/mnt/home/munge.key',
          source => '/etc/munge/munge.key',
          owner  => 'munge',
          mode   => '0400';
    }
  }
  elsif (not is_file '/mnt/home/munge.key') {
      # copy from head node
      file '/etc/munge/munge.key',
        source => '/mnt/home/munge.key',
        owner  => 'munge',
        mode   => '0400';
  }

  # set proper permissions, applied to all nodes
  chown "munge", "/etc/munge/munge.key";
  chmod "0400", "/etc/munge/munge.key";
  service "munge" => "ensure", "start";
};

desc "Query time";
task "query_time", group => "allnodes", sub {
  say run "date +%s";
};
