use Rex -feature => [qw/1.4 exec_autodie/];

# Define the host groups
group head     => 'compute01';
group workers  => 'compute02', 'compute03';
group allnodes => 'compute01', 'compute02', 'compute03';

# Set the SSH user (replace with your actual username)
user "user";
sudo TRUE;
sudo_password "$ENV{SUDOPASS}";

# Main task to install and configure Chrony
desc "Ensure slurm is installed and configured";
task "setup_slurm", group => "allnodes", sub {
  my $hostname = connection->server;
  my $is_head  = ($hostname eq 'compute01');

  say run "uname -a";

  # Install Slurm and munge 
  pkg "slurm-wlm", ensure => "present";
  pkg "munge",     ensure => "present";

  if ($is_head) {
    # generate munge key on head node
    run "mungekey --create --force";

    # set proper permissions, applied to all nodes
    chown "munge", "/etc/munge/munge.key";
    chmod "0644", "/etc/munge/munge.key";

    cp "/etc/munge/munge.key", "/home/user/adcirc-cluster/slurm-setup/rex-slurm/munge.key";

    # write slurm.conf on head node
    file  "/etc/slurm/slurm.conf",
      source => "files/slurm.conf",
      owner  => "slurm",
      mode   => "0644";

    # sudo mkdir -p /var/spool/slurmctld /var/spool/slurmd
    # sudo chown slurm: /var/spool/slurmctld /var/spool/slurmd
    foreach my $dir (qw{/var/spool/slurmctld /var/spool/slurmd}) {
      file $dir,
        ensure => "directory",
        owner  => "slurm",
        group  => "slurm",
        mode   => "0750";
    }

    run "pkill munge || echo";
    service "munge" => "ensure", "started";

    chmod "0400", "/etc/munge/munge.key";
    run "pkill munge || echo";
    service "munge" => "ensure", "started";

    run "pkill slurmctld || echo";
    service "slurmctld" => "ensure", "started"; # start controller node
  }
  else {

    # ensure munge key is not there
    file "/etc/munge/munge.key",
      ensure => "absent";

    # copy to make available on other nodes
    file "/etc/munge/munge.key",
      source => "/home/user/adcirc-cluster/slurm-setup/rex-slurm/munge.key",
      owner  => "munge",
      mode   => "0644";

    # write slurm.conf on head node
    file  "/etc/slurm/slurm.conf",
      source => "files/slurm.conf",
      owner  => "slurm",
      mode   => "0644";

    # sudo mkdir -p /var/spool/slurmctld /var/spool/slurmd
    # sudo chown slurm: /var/spool/slurmctld /var/spool/slurmd
    foreach my $dir (qw{/var/spool/slurmctld /var/spool/slurmd}) {
      file $dir,
        ensure => "directory",
        owner  => "slurm",
        group  => "slurm",
        mode   => "0750";
    }

    # set proper permissions, applied to all nodes
    chown "root", "/etc/munge";
    chmod "0755", "/etc/munge";

    chmod "0400", "/etc/munge/munge.key";
    run "pkill munge || echo";
    service "munge" => "ensure", "started";
  }

  run "pkill slurmd || echo";
  service "slurmd" => "ensure", "start";      # start as compute node
};

desc "Query time";
task "query_time", group => "allnodes", sub {
  say run "date +%s";
};
