use Rex -feature => [qw/1.4 exec_autodie/];

# Define the host groups
group head     => 'compute01';
group workers  => 'compute02', 'compute03';
group allnodes => 'compute01', 'compute02', 'compute03';

# Set the SSH user (replace with your actual username)
user "user";
sudo TRUE;
sudo_password "$ENV{SUDOPASS}";

# Main task to install and configure Chrony
desc "Ensure chrony is installed and configured";
task "setup_chrony", group => "allnodes", sub {
  my $hostname = connection->server;
  my $is_head  = ($hostname eq 'compute01');

  say run "uname -a";

  # Install Chrony
  pkg "chrony", ensure => "present";

  # Push correct config file
  file "/etc/chrony/chrony.conf",
    source => $is_head ? "files/chrony-head.conf" : "files/chrony-worker.conf",
    owner  => "root",
    group  => "root",
    mode   => 0644;

  # Enable and start Chrony service
  service "chrony" => "ensure", "start";
};

desc "Query time";
task "query_time", group => "allnodes", sub {
  say run "date +%s";
};
